# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('redist_rcpp_hello_world', PACKAGE = 'redist')
}

pBias <- function(ndem, nrep, cdMat, swing) {
    .Call('redist_pBias', PACKAGE = 'redist', ndem, nrep, cdMat, swing)
}

checkRecip <- function(aList) {
    .Call('redist_checkRecip', PACKAGE = 'redist', aList)
}

addTies <- function(aList) {
    .Call('redist_addTies', PACKAGE = 'redist', aList)
}

genCC <- function(aList, cutList) {
    .Call('redist_genCC', PACKAGE = 'redist', aList, cutList)
}

genCC2 <- function(aList, cds, zeroInd = 1L) {
    .Call('redist_genCC2', PACKAGE = 'redist', aList, cds, zeroInd)
}

bSearchCppBound <- function(adjList, tractnum, boundaryindex) {
    .Call('redist_bSearchCppBound', PACKAGE = 'redist', adjList, tractnum, boundaryindex)
}

getBoundary <- function(list) {
    .Call('redist_getBoundary', PACKAGE = 'redist', list)
}

getBoundary2 <- function(fullList, conList) {
    .Call('redist_getBoundary2', PACKAGE = 'redist', fullList, conList)
}

getCds <- function(fullList, boundInds, cds) {
    .Call('redist_getCds', PACKAGE = 'redist', fullList, boundInds, cds)
}

genCutC <- function(aList, cds) {
    .Call('redist_genCutC', PACKAGE = 'redist', aList, cds)
}

getAdj <- function(aList, unitVec, cdVec, cd) {
    .Call('redist_getAdj', PACKAGE = 'redist', aList, unitVec, cdVec, cd)
}

popCalc <- function(switchPartition, pops, distPops, oldCd, newCd) {
    .Call('redist_popCalc', PACKAGE = 'redist', switchPartition, pops, distPops, oldCd, newCd)
}

swMH <- function(aList, cds, nrep, eprob, pops, grouppop, parity, margin, dists, lambda, ssd, beta, betadiss, betapop, betavec, betadissvec, betapopvec, origpartcompact = 0L, annealbeta = 0L, annealbetadiss = 0L, annealbetapop = 0L, elimCheck = 1L) {
    .Call('redist_swMH', PACKAGE = 'redist', aList, cds, nrep, eprob, pops, grouppop, parity, margin, dists, lambda, ssd, beta, betadiss, betapop, betavec, betadissvec, betapopvec, origpartcompact, annealbeta, annealbetadiss, annealbetapop, elimCheck)
}

