// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "redist_types.h"
#include <RcppArmadillo.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// reduce_adj
List reduce_adj(List adj_list, IntegerVector prec_map, int n_keep);
RcppExport SEXP _redist_reduce_adj(SEXP adj_listSEXP, SEXP prec_mapSEXP, SEXP n_keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type prec_map(prec_mapSEXP);
    Rcpp::traits::input_parameter< int >::type n_keep(n_keepSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_adj(adj_list, prec_map, n_keep));
    return rcpp_result_gen;
END_RCPP
}
// collapse_adj
Graph collapse_adj(List graph, const arma::uvec& idxs);
RcppExport SEXP _redist_collapse_adj(SEXP graphSEXP, SEXP idxsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type idxs(idxsSEXP);
    rcpp_result_gen = Rcpp::wrap(collapse_adj(graph, idxs));
    return rcpp_result_gen;
END_RCPP
}
// coarsen_adjacency
List coarsen_adjacency(List adj, IntegerVector groups);
RcppExport SEXP _redist_coarsen_adjacency(SEXP adjSEXP, SEXP groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(coarsen_adjacency(adj, groups));
    return rcpp_result_gen;
END_RCPP
}
// get_plan_graph
std::vector<std::set<int>> get_plan_graph(List l, int V, IntegerVector plan, int n_distr);
RcppExport SEXP _redist_get_plan_graph(SEXP lSEXP, SEXP VSEXP, SEXP planSEXP, SEXP n_distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l(lSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type plan(planSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    rcpp_result_gen = Rcpp::wrap(get_plan_graph(l, V, plan, n_distr));
    return rcpp_result_gen;
END_RCPP
}
// color_graph
IntegerVector color_graph(List l, IntegerVector plan);
RcppExport SEXP _redist_color_graph(SEXP lSEXP, SEXP planSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l(lSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type plan(planSEXP);
    rcpp_result_gen = Rcpp::wrap(color_graph(l, plan));
    return rcpp_result_gen;
END_RCPP
}
// polsbypopper
NumericMatrix polsbypopper(IntegerVector from, IntegerVector to, NumericVector area, NumericVector perimeter, IntegerMatrix dm, int nd);
RcppExport SEXP _redist_polsbypopper(SEXP fromSEXP, SEXP toSEXP, SEXP areaSEXP, SEXP perimeterSEXP, SEXP dmSEXP, SEXP ndSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type area(areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type perimeter(perimeterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< int >::type nd(ndSEXP);
    rcpp_result_gen = Rcpp::wrap(polsbypopper(from, to, area, perimeter, dm, nd));
    return rcpp_result_gen;
END_RCPP
}
// genAlConn
List genAlConn(List aList, NumericVector cds);
RcppExport SEXP _redist_genAlConn(SEXP aListSEXP, SEXP cdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type aList(aListSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cds(cdsSEXP);
    rcpp_result_gen = Rcpp::wrap(genAlConn(aList, cds));
    return rcpp_result_gen;
END_RCPP
}
// findBoundary
NumericVector findBoundary(List fullList, List conList);
RcppExport SEXP _redist_findBoundary(SEXP fullListSEXP, SEXP conListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type fullList(fullListSEXP);
    Rcpp::traits::input_parameter< List >::type conList(conListSEXP);
    rcpp_result_gen = Rcpp::wrap(findBoundary(fullList, conList));
    return rcpp_result_gen;
END_RCPP
}
// contiguity
IntegerVector contiguity(List adj, IntegerVector group);
RcppExport SEXP _redist_contiguity(SEXP adjSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(contiguity(adj, group));
    return rcpp_result_gen;
END_RCPP
}
// cores
List cores(List adj, IntegerVector dm, int k, List cd_within_k);
RcppExport SEXP _redist_cores(SEXP adjSEXP, SEXP dmSEXP, SEXP kSEXP, SEXP cd_within_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< List >::type cd_within_k(cd_within_kSEXP);
    rcpp_result_gen = Rcpp::wrap(cores(adj, dm, k, cd_within_k));
    return rcpp_result_gen;
END_RCPP
}
// update_conncomp
IntegerVector update_conncomp(IntegerVector dm, IntegerVector kvec, List adj);
RcppExport SEXP _redist_update_conncomp(SEXP dmSEXP, SEXP kvecSEXP, SEXP adjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type kvec(kvecSEXP);
    Rcpp::traits::input_parameter< List >::type adj(adjSEXP);
    rcpp_result_gen = Rcpp::wrap(update_conncomp(dm, kvec, adj));
    return rcpp_result_gen;
END_RCPP
}
// crsg
List crsg(List adj_list, NumericVector population, NumericVector area, NumericVector x_center, NumericVector y_center, int Ndistrict, double target_pop, double thresh, int maxiter);
RcppExport SEXP _redist_crsg(SEXP adj_listSEXP, SEXP populationSEXP, SEXP areaSEXP, SEXP x_centerSEXP, SEXP y_centerSEXP, SEXP NdistrictSEXP, SEXP target_popSEXP, SEXP threshSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type population(populationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type area(areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_center(x_centerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_center(y_centerSEXP);
    Rcpp::traits::input_parameter< int >::type Ndistrict(NdistrictSEXP);
    Rcpp::traits::input_parameter< double >::type target_pop(target_popSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(crsg(adj_list, population, area, x_center, y_center, Ndistrict, target_pop, thresh, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// dist_dist_diff
double dist_dist_diff(int p, int i_dist, int j_dist, NumericVector x_center, NumericVector y_center, NumericVector x, NumericVector y);
RcppExport SEXP _redist_dist_dist_diff(SEXP pSEXP, SEXP i_distSEXP, SEXP j_distSEXP, SEXP x_centerSEXP, SEXP y_centerSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type i_dist(i_distSEXP);
    Rcpp::traits::input_parameter< int >::type j_dist(j_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_center(x_centerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_center(y_centerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dist_dist_diff(p, i_dist, j_dist, x_center, y_center, x, y));
    return rcpp_result_gen;
END_RCPP
}
// get_region_multigraph
RegionMultigraphCount get_region_multigraph(Rcpp::List const& adj_list, arma::uvec const& region_ids);
RcppExport SEXP _redist_get_region_multigraph(SEXP adj_listSEXP, SEXP region_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type region_ids(region_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_region_multigraph(adj_list, region_ids));
    return rcpp_result_gen;
END_RCPP
}
// get_region_laplacian
arma::mat get_region_laplacian(Rcpp::List const& adj_list, arma::uvec const& region_ids);
RcppExport SEXP _redist_get_region_laplacian(SEXP adj_listSEXP, SEXP region_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type region_ids(region_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_region_laplacian(adj_list, region_ids));
    return rcpp_result_gen;
END_RCPP
}
// get_log_number_linking_edges
double get_log_number_linking_edges(Rcpp::List const& adj_list, arma::uvec const& region_ids);
RcppExport SEXP _redist_get_log_number_linking_edges(SEXP adj_listSEXP, SEXP region_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type region_ids(region_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_log_number_linking_edges(adj_list, region_ids));
    return rcpp_result_gen;
END_RCPP
}
// get_merged_log_number_linking_edges
double get_merged_log_number_linking_edges(Rcpp::List const& adj_list, arma::uvec const& region_ids, int const region1_id, int const region2_id);
RcppExport SEXP _redist_get_merged_log_number_linking_edges(SEXP adj_listSEXP, SEXP region_idsSEXP, SEXP region1_idSEXP, SEXP region2_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< int const >::type region1_id(region1_idSEXP);
    Rcpp::traits::input_parameter< int const >::type region2_id(region2_idSEXP);
    rcpp_result_gen = Rcpp::wrap(get_merged_log_number_linking_edges(adj_list, region_ids, region1_id, region2_id));
    return rcpp_result_gen;
END_RCPP
}
// log_st_map
NumericVector log_st_map(const Graph& g, const arma::umat& districts, const arma::uvec& counties, int n_distr);
RcppExport SEXP _redist_log_st_map(SEXP gSEXP, SEXP districtsSEXP, SEXP countiesSEXP, SEXP n_distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Graph& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    rcpp_result_gen = Rcpp::wrap(log_st_map(g, districts, counties, n_distr));
    return rcpp_result_gen;
END_RCPP
}
// n_removed
NumericVector n_removed(const Graph& g, const arma::umat& districts, int n_distr);
RcppExport SEXP _redist_n_removed(SEXP gSEXP, SEXP districtsSEXP, SEXP n_distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Graph& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    rcpp_result_gen = Rcpp::wrap(n_removed(g, districts, n_distr));
    return rcpp_result_gen;
END_RCPP
}
// countpartitions
int countpartitions(List aList);
RcppExport SEXP _redist_countpartitions(SEXP aListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type aList(aListSEXP);
    rcpp_result_gen = Rcpp::wrap(countpartitions(aList));
    return rcpp_result_gen;
END_RCPP
}
// calcPWDh
NumericMatrix calcPWDh(NumericMatrix x);
RcppExport SEXP _redist_calcPWDh(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calcPWDh(x));
    return rcpp_result_gen;
END_RCPP
}
// draw_a_tree_on_a_region
List draw_a_tree_on_a_region(List adj_list, const arma::uvec& counties, const arma::uvec& pop, int ndists, int num_regions, int num_districts, int region_id_to_draw_tree_on, double lower, double upper, Rcpp::IntegerMatrix const& region_ids, Rcpp::IntegerMatrix const& region_sizes, bool verbose);
RcppExport SEXP _redist_draw_a_tree_on_a_region(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP ndistsSEXP, SEXP num_regionsSEXP, SEXP num_districtsSEXP, SEXP region_id_to_draw_tree_onSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< int >::type num_districts(num_districtsSEXP);
    Rcpp::traits::input_parameter< int >::type region_id_to_draw_tree_on(region_id_to_draw_tree_onSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(draw_a_tree_on_a_region(adj_list, counties, pop, ndists, num_regions, num_districts, region_id_to_draw_tree_on, lower, upper, region_ids, region_sizes, verbose));
    return rcpp_result_gen;
END_RCPP
}
// perform_a_valid_multidistrict_split
List perform_a_valid_multidistrict_split(List adj_list, const arma::uvec& counties, const arma::uvec& pop, int ndists, int num_regions, int num_districts, int region_id_to_split, double target, double lower, double upper, Rcpp::IntegerMatrix const& region_ids, Rcpp::IntegerMatrix const& region_sizes, int split_dval_min, int split_dval_max, bool split_district_only, bool verbose, int k_param);
RcppExport SEXP _redist_perform_a_valid_multidistrict_split(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP ndistsSEXP, SEXP num_regionsSEXP, SEXP num_districtsSEXP, SEXP region_id_to_splitSEXP, SEXP targetSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP split_dval_minSEXP, SEXP split_dval_maxSEXP, SEXP split_district_onlySEXP, SEXP verboseSEXP, SEXP k_paramSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< int >::type num_districts(num_districtsSEXP);
    Rcpp::traits::input_parameter< int >::type region_id_to_split(region_id_to_splitSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< int >::type split_dval_min(split_dval_minSEXP);
    Rcpp::traits::input_parameter< int >::type split_dval_max(split_dval_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type split_district_only(split_district_onlySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type k_param(k_paramSEXP);
    rcpp_result_gen = Rcpp::wrap(perform_a_valid_multidistrict_split(adj_list, counties, pop, ndists, num_regions, num_districts, region_id_to_split, target, lower, upper, region_ids, region_sizes, split_dval_min, split_dval_max, split_district_only, verbose, k_param));
    return rcpp_result_gen;
END_RCPP
}
// draw_trees_on_a_region
List draw_trees_on_a_region(List const& adj_list, const arma::uvec& counties, const arma::uvec& pop, int const ndists, int const region_id_to_draw_tree_on, int const region_size, double const lower, double const target, double const upper, arma::uvec const& region_ids, int const num_tree, int num_threads, bool const verbose);
RcppExport SEXP _redist_draw_trees_on_a_region(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP ndistsSEXP, SEXP region_id_to_draw_tree_onSEXP, SEXP region_sizeSEXP, SEXP lowerSEXP, SEXP targetSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP num_treeSEXP, SEXP num_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int const >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int const >::type region_id_to_draw_tree_on(region_id_to_draw_tree_onSEXP);
    Rcpp::traits::input_parameter< int const >::type region_size(region_sizeSEXP);
    Rcpp::traits::input_parameter< double const >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double const >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double const >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< int const >::type num_tree(num_treeSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool const >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(draw_trees_on_a_region(adj_list, counties, pop, ndists, region_id_to_draw_tree_on, region_size, lower, target, upper, region_ids, num_tree, num_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// attempt_splits_on_a_region
List attempt_splits_on_a_region(List const& adj_list, const arma::uvec& counties, const arma::uvec& pop, int const ndists, int const init_num_regions, int const region_id_to_split, double const lower, double const target, double const upper, Rcpp::IntegerMatrix const& region_ids, Rcpp::IntegerMatrix const& region_sizes, std::string const& splitting_schedule_str, int const k_param, int const num_plans, int num_threads, bool const verbose);
RcppExport SEXP _redist_attempt_splits_on_a_region(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP ndistsSEXP, SEXP init_num_regionsSEXP, SEXP region_id_to_splitSEXP, SEXP lowerSEXP, SEXP targetSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP splitting_schedule_strSEXP, SEXP k_paramSEXP, SEXP num_plansSEXP, SEXP num_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int const >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int const >::type init_num_regions(init_num_regionsSEXP);
    Rcpp::traits::input_parameter< int const >::type region_id_to_split(region_id_to_splitSEXP);
    Rcpp::traits::input_parameter< double const >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double const >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double const >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< std::string const& >::type splitting_schedule_str(splitting_schedule_strSEXP);
    Rcpp::traits::input_parameter< int const >::type k_param(k_paramSEXP);
    Rcpp::traits::input_parameter< int const >::type num_plans(num_plansSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool const >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(attempt_splits_on_a_region(adj_list, counties, pop, ndists, init_num_regions, region_id_to_split, lower, target, upper, region_ids, region_sizes, splitting_schedule_str, k_param, num_plans, num_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// compute_log_unnormalized_plan_target_density
Rcpp::NumericVector compute_log_unnormalized_plan_target_density(List const& adj_list, const arma::uvec& counties, const arma::uvec& pop, List const& constraints, double const pop_temper, double const rho, int const ndists, int const total_seats, int const num_regions, Rcpp::IntegerVector const& district_seat_sizes, double const lower, double const target, double const upper, Rcpp::IntegerMatrix const& region_ids, Rcpp::IntegerMatrix const& region_sizes, int const num_threads);
RcppExport SEXP _redist_compute_log_unnormalized_plan_target_density(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP constraintsSEXP, SEXP pop_temperSEXP, SEXP rhoSEXP, SEXP ndistsSEXP, SEXP total_seatsSEXP, SEXP num_regionsSEXP, SEXP district_seat_sizesSEXP, SEXP lowerSEXP, SEXP targetSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< List const& >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< double const >::type pop_temper(pop_temperSEXP);
    Rcpp::traits::input_parameter< double const >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int const >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int const >::type total_seats(total_seatsSEXP);
    Rcpp::traits::input_parameter< int const >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector const& >::type district_seat_sizes(district_seat_sizesSEXP);
    Rcpp::traits::input_parameter< double const >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double const >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double const >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_log_unnormalized_plan_target_density(adj_list, counties, pop, constraints, pop_temper, rho, ndists, total_seats, num_regions, district_seat_sizes, lower, target, upper, region_ids, region_sizes, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// compute_log_unnormalized_region_target_density
Rcpp::NumericMatrix compute_log_unnormalized_region_target_density(List const& adj_list, const arma::uvec& counties, const arma::uvec& pop, List const& constraints, double const pop_temper, double const rho, int const ndists, int const total_seats, int const num_regions, Rcpp::IntegerVector const& district_seat_sizes, double const lower, double const target, double const upper, Rcpp::IntegerMatrix const& region_ids, Rcpp::IntegerMatrix const& region_sizes, int const num_threads);
RcppExport SEXP _redist_compute_log_unnormalized_region_target_density(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP constraintsSEXP, SEXP pop_temperSEXP, SEXP rhoSEXP, SEXP ndistsSEXP, SEXP total_seatsSEXP, SEXP num_regionsSEXP, SEXP district_seat_sizesSEXP, SEXP lowerSEXP, SEXP targetSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< List const& >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< double const >::type pop_temper(pop_temperSEXP);
    Rcpp::traits::input_parameter< double const >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int const >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int const >::type total_seats(total_seatsSEXP);
    Rcpp::traits::input_parameter< int const >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector const& >::type district_seat_sizes(district_seat_sizesSEXP);
    Rcpp::traits::input_parameter< double const >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double const >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double const >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_log_unnormalized_region_target_density(adj_list, counties, pop, constraints, pop_temper, rho, ndists, total_seats, num_regions, district_seat_sizes, lower, target, upper, region_ids, region_sizes, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// compute_plans_log_optimal_weights
arma::vec compute_plans_log_optimal_weights(List const& adj_list, arma::uvec const& counties, arma::uvec const& pop, List const& constraints, double const pop_temper, double const rho, std::string const& splitting_schedule_str, int const ndists, int const total_seats, Rcpp::IntegerVector const& district_seat_sizes, int const num_regions, double const lower, double const target, double const upper, Rcpp::IntegerMatrix const& region_ids, Rcpp::IntegerMatrix const& region_sizes, int num_threads);
RcppExport SEXP _redist_compute_plans_log_optimal_weights(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP constraintsSEXP, SEXP pop_temperSEXP, SEXP rhoSEXP, SEXP splitting_schedule_strSEXP, SEXP ndistsSEXP, SEXP total_seatsSEXP, SEXP district_seat_sizesSEXP, SEXP num_regionsSEXP, SEXP lowerSEXP, SEXP targetSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< List const& >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< double const >::type pop_temper(pop_temperSEXP);
    Rcpp::traits::input_parameter< double const >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< std::string const& >::type splitting_schedule_str(splitting_schedule_strSEXP);
    Rcpp::traits::input_parameter< int const >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int const >::type total_seats(total_seatsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector const& >::type district_seat_sizes(district_seat_sizesSEXP);
    Rcpp::traits::input_parameter< int const >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< double const >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double const >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double const >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_plans_log_optimal_weights(adj_list, counties, pop, constraints, pop_temper, rho, splitting_schedule_str, ndists, total_seats, district_seat_sizes, num_regions, lower, target, upper, region_ids, region_sizes, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// group_pct_top_k
NumericVector group_pct_top_k(const IntegerMatrix m, const NumericVector group_pop, const NumericVector total_pop, int k, int n_distr);
RcppExport SEXP _redist_group_pct_top_k(SEXP mSEXP, SEXP group_popSEXP, SEXP total_popSEXP, SEXP kSEXP, SEXP n_distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type group_pop(group_popSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type total_pop(total_popSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    rcpp_result_gen = Rcpp::wrap(group_pct_top_k(m, group_pop, total_pop, k, n_distr));
    return rcpp_result_gen;
END_RCPP
}
// proj_distr_m
NumericMatrix proj_distr_m(IntegerMatrix districts, const arma::vec x, IntegerVector draw_idx, int n_distr);
RcppExport SEXP _redist_proj_distr_m(SEXP districtsSEXP, SEXP xSEXP, SEXP draw_idxSEXP, SEXP n_distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type draw_idx(draw_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    rcpp_result_gen = Rcpp::wrap(proj_distr_m(districts, x, draw_idx, n_distr));
    return rcpp_result_gen;
END_RCPP
}
// colmax
NumericVector colmax(const NumericMatrix x);
RcppExport SEXP _redist_colmax(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colmax(x));
    return rcpp_result_gen;
END_RCPP
}
// colmin
NumericVector colmin(const NumericMatrix x);
RcppExport SEXP _redist_colmin(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colmin(x));
    return rcpp_result_gen;
END_RCPP
}
// prec_cooccur
arma::mat prec_cooccur(arma::umat m, arma::uvec idxs, int ncores);
RcppExport SEXP _redist_prec_cooccur(SEXP mSEXP, SEXP idxsSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type idxs(idxsSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(prec_cooccur(m, idxs, ncores));
    return rcpp_result_gen;
END_RCPP
}
// group_pct
NumericMatrix group_pct(IntegerMatrix const& plans_mat, arma::vec const& group_pop, arma::vec const& total_pop, int const n_distr, int const num_threads);
RcppExport SEXP _redist_group_pct(SEXP plans_matSEXP, SEXP group_popSEXP, SEXP total_popSEXP, SEXP n_distrSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix const& >::type plans_mat(plans_matSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type group_pop(group_popSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type total_pop(total_popSEXP);
    Rcpp::traits::input_parameter< int const >::type n_distr(n_distrSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(group_pct(plans_mat, group_pop, total_pop, n_distr, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// pop_tally
NumericMatrix pop_tally(IntegerMatrix const& districts, arma::vec const& pop, int const n_distr, int const num_threads);
RcppExport SEXP _redist_pop_tally(SEXP districtsSEXP, SEXP popSEXP, SEXP n_distrSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix const& >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int const >::type n_distr(n_distrSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pop_tally(districts, pop, n_distr, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// infer_region_sizes
Rcpp::IntegerMatrix infer_region_sizes(Rcpp::IntegerMatrix const& region_pops, double const lower, double const upper, int const total_seats, int const num_threads);
RcppExport SEXP _redist_infer_region_sizes(SEXP region_popsSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP total_seatsSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_pops(region_popsSEXP);
    Rcpp::traits::input_parameter< double const >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double const >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int const >::type total_seats(total_seatsSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(infer_region_sizes(region_pops, lower, upper, total_seats, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// max_dev
NumericVector max_dev(const IntegerMatrix& districts, const arma::vec& pop, int const n_distr, int const num_threads);
RcppExport SEXP _redist_max_dev(SEXP districtsSEXP, SEXP popSEXP, SEXP n_distrSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int const >::type n_distr(n_distrSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(max_dev(districts, pop, n_distr, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// order_district_stats
Rcpp::NumericVector order_district_stats(Rcpp::NumericVector const& district_stats, int const ndists, int const num_threads);
RcppExport SEXP _redist_order_district_stats(SEXP district_statsSEXP, SEXP ndistsSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type district_stats(district_statsSEXP);
    Rcpp::traits::input_parameter< int const >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(order_district_stats(district_stats, ndists, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_n_removed
NumericVector parallel_n_removed(const Graph& g, const IntegerMatrix& districts, int const n_distr, int const num_threads);
RcppExport SEXP _redist_parallel_n_removed(SEXP gSEXP, SEXP districtsSEXP, SEXP n_distrSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Graph& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< int const >::type n_distr(n_distrSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_n_removed(g, districts, n_distr, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_effgap
NumericVector parallel_effgap(NumericMatrix const& dcounts, NumericMatrix const& rcounts, int const totvote, int const num_threads);
RcppExport SEXP _redist_parallel_effgap(SEXP dcountsSEXP, SEXP rcountsSEXP, SEXP totvoteSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix const& >::type dcounts(dcountsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix const& >::type rcounts(rcountsSEXP);
    Rcpp::traits::input_parameter< int const >::type totvote(totvoteSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_effgap(dcounts, rcounts, totvote, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_agg_p2d
NumericMatrix parallel_agg_p2d(IntegerMatrix const& dm, NumericVector const& vote, int const nd, int const num_threads);
RcppExport SEXP _redist_parallel_agg_p2d(SEXP dmSEXP, SEXP voteSEXP, SEXP ndSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< IntegerMatrix const& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type vote(voteSEXP);
    Rcpp::traits::input_parameter< int const >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_agg_p2d(dm, vote, nd, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_biasatv
NumericVector parallel_biasatv(NumericMatrix const& dvs, double const v, int const nd, int const num_threads);
RcppExport SEXP _redist_parallel_biasatv(SEXP dvsSEXP, SEXP vSEXP, SEXP ndSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix const& >::type dvs(dvsSEXP);
    Rcpp::traits::input_parameter< double const >::type v(vSEXP);
    Rcpp::traits::input_parameter< int const >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_biasatv(dvs, v, nd, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallelDVS
NumericMatrix parallelDVS(NumericMatrix const& dcounts, NumericMatrix const& rcounts, int const num_threads);
RcppExport SEXP _redist_parallelDVS(SEXP dcountsSEXP, SEXP rcountsSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix const& >::type dcounts(dcountsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix const& >::type rcounts(rcountsSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallelDVS(dcounts, rcounts, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_splits
Rcpp::IntegerVector parallel_splits(const IntegerMatrix& dm, const IntegerVector& community, int const nd, int const max_split, int const num_threads, bool const skip_last);
RcppExport SEXP _redist_parallel_splits(SEXP dmSEXP, SEXP communitySEXP, SEXP ndSEXP, SEXP max_splitSEXP, SEXP num_threadsSEXP, SEXP skip_lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type community(communitySEXP);
    Rcpp::traits::input_parameter< int const >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int const >::type max_split(max_splitSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool const >::type skip_last(skip_lastSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_splits(dm, community, nd, max_split, num_threads, skip_last));
    return rcpp_result_gen;
END_RCPP
}
// parallel_polsbypopper
NumericMatrix parallel_polsbypopper(IntegerVector const& from, IntegerVector const& to, NumericVector const& area, NumericVector const& perimeter, IntegerMatrix const& dm, int const nd, int const num_threads);
RcppExport SEXP _redist_parallel_polsbypopper(SEXP fromSEXP, SEXP toSEXP, SEXP areaSEXP, SEXP perimeterSEXP, SEXP dmSEXP, SEXP ndSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< IntegerVector const& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector const& >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type area(areaSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type perimeter(perimeterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix const& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< int const >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_polsbypopper(from, to, area, perimeter, dm, nd, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// ms_plans
Rcpp::List ms_plans(int const nsims, int const warmup, int const thin, int const ndists, int const total_seats, Rcpp::IntegerVector const& district_seat_sizes, List const& adj_list, const arma::uvec& counties, const arma::uvec& pop, double const target, double const lower, double const upper, double const rho, Rcpp::IntegerMatrix const& initial_plan, Rcpp::IntegerMatrix const& initial_region_sizes, std::string const& sampling_space_str, std::string const& merge_prob_type, List const& control, List const& constraints, int const verbosity, bool const diagnostic_mode);
RcppExport SEXP _redist_ms_plans(SEXP nsimsSEXP, SEXP warmupSEXP, SEXP thinSEXP, SEXP ndistsSEXP, SEXP total_seatsSEXP, SEXP district_seat_sizesSEXP, SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP targetSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP rhoSEXP, SEXP initial_planSEXP, SEXP initial_region_sizesSEXP, SEXP sampling_space_strSEXP, SEXP merge_prob_typeSEXP, SEXP controlSEXP, SEXP constraintsSEXP, SEXP verbositySEXP, SEXP diagnostic_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int const >::type nsims(nsimsSEXP);
    Rcpp::traits::input_parameter< int const >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< int const >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int const >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int const >::type total_seats(total_seatsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector const& >::type district_seat_sizes(district_seat_sizesSEXP);
    Rcpp::traits::input_parameter< List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< double const >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double const >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double const >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double const >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type initial_plan(initial_planSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type initial_region_sizes(initial_region_sizesSEXP);
    Rcpp::traits::input_parameter< std::string const& >::type sampling_space_str(sampling_space_strSEXP);
    Rcpp::traits::input_parameter< std::string const& >::type merge_prob_type(merge_prob_typeSEXP);
    Rcpp::traits::input_parameter< List const& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< List const& >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< int const >::type verbosity(verbositySEXP);
    Rcpp::traits::input_parameter< bool const >::type diagnostic_mode(diagnostic_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(ms_plans(nsims, warmup, thin, ndists, total_seats, district_seat_sizes, adj_list, counties, pop, target, lower, upper, rho, initial_plan, initial_region_sizes, sampling_space_str, merge_prob_type, control, constraints, verbosity, diagnostic_mode));
    return rcpp_result_gen;
END_RCPP
}
// pareto_dominated
LogicalVector pareto_dominated(arma::mat x);
RcppExport SEXP _redist_pareto_dominated(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pareto_dominated(x));
    return rcpp_result_gen;
END_RCPP
}
// random_cpp_testing
Rcpp::List random_cpp_testing();
RcppExport SEXP _redist_random_cpp_testing() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(random_cpp_testing());
    return rcpp_result_gen;
END_RCPP
}
// split_schedule_testing
void split_schedule_testing(int num_presplit_regions);
RcppExport SEXP _redist_split_schedule_testing(SEXP num_presplit_regionsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_presplit_regions(num_presplit_regionsSEXP);
    split_schedule_testing(num_presplit_regions);
    return R_NilValue;
END_RCPP
}
// matrix_reorder_testing
arma::imat matrix_reorder_testing(arma::imat& test_mat, arma::uvec const& reorder_vec);
RcppExport SEXP _redist_matrix_reorder_testing(SEXP test_matSEXP, SEXP reorder_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat& >::type test_mat(test_matSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type reorder_vec(reorder_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_reorder_testing(test_mat, reorder_vec));
    return rcpp_result_gen;
END_RCPP
}
// NEW_matrix_reorder_testing
void NEW_matrix_reorder_testing(Rcpp::IntegerMatrix& test_mat, arma::uvec const& reorder_vec);
RcppExport SEXP _redist_NEW_matrix_reorder_testing(SEXP test_matSEXP, SEXP reorder_vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type test_mat(test_matSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type reorder_vec(reorder_vecSEXP);
    NEW_matrix_reorder_testing(test_mat, reorder_vec);
    return R_NilValue;
END_RCPP
}
// more_random_cpp_testing
List more_random_cpp_testing();
RcppExport SEXP _redist_more_random_cpp_testing() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(more_random_cpp_testing());
    return rcpp_result_gen;
END_RCPP
}
// calc_county_dist_test
std::vector<std::set<int>> calc_county_dist_test(const arma::umat& districts_mat, const arma::uvec& counties, int n_cty, bool zero_ok);
RcppExport SEXP _redist_calc_county_dist_test(SEXP districts_matSEXP, SEXP countiesSEXP, SEXP n_ctySEXP, SEXP zero_okSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type districts_mat(districts_matSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< int >::type n_cty(n_ctySEXP);
    Rcpp::traits::input_parameter< bool >::type zero_ok(zero_okSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_county_dist_test(districts_mat, counties, n_cty, zero_ok));
    return rcpp_result_gen;
END_RCPP
}
// calc_splits_test
arma::uvec calc_splits_test(const arma::umat& districts_mat, const arma::uvec& counties, int n_cty, int num_threads);
RcppExport SEXP _redist_calc_splits_test(SEXP districts_matSEXP, SEXP countiesSEXP, SEXP n_ctySEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type districts_mat(districts_matSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< int >::type n_cty(n_ctySEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_splits_test(districts_mat, counties, n_cty, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// closest_adj_pop
int closest_adj_pop(IntegerVector adj, int i_dist, NumericVector g_prop);
RcppExport SEXP _redist_closest_adj_pop(SEXP adjSEXP, SEXP i_distSEXP, SEXP g_propSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< int >::type i_dist(i_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g_prop(g_propSEXP);
    rcpp_result_gen = Rcpp::wrap(closest_adj_pop(adj, i_dist, g_prop));
    return rcpp_result_gen;
END_RCPP
}
// rint1
Rcpp::IntegerVector rint1(int n, int max);
RcppExport SEXP _redist_rint1(SEXP nSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(rint1(n, max));
    return rcpp_result_gen;
END_RCPP
}
// runif1
Rcpp::NumericVector runif1(int n, int max);
RcppExport SEXP _redist_runif1(SEXP nSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(runif1(n, max));
    return rcpp_result_gen;
END_RCPP
}
// resample_lowvar
arma::ivec resample_lowvar(arma::vec wgts);
RcppExport SEXP _redist_resample_lowvar(SEXP wgtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type wgts(wgtsSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_lowvar(wgts));
    return rcpp_result_gen;
END_RCPP
}
// maximum_input_sizes
Rcpp::List maximum_input_sizes();
RcppExport SEXP _redist_maximum_input_sizes() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(maximum_input_sizes());
    return rcpp_result_gen;
END_RCPP
}
// get_canonical_plan_labelling
Rcpp::IntegerMatrix get_canonical_plan_labelling(Rcpp::IntegerMatrix const& plans_mat, int const num_regions, int const num_threads);
RcppExport SEXP _redist_get_canonical_plan_labelling(SEXP plans_matSEXP, SEXP num_regionsSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type plans_mat(plans_matSEXP);
    Rcpp::traits::input_parameter< int const >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_canonical_plan_labelling(plans_mat, num_regions, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// resample_plans_lowvar
Rcpp::IntegerVector resample_plans_lowvar(Rcpp::NumericVector const& normalized_weights, Rcpp::IntegerMatrix& plans_mat, Rcpp::IntegerMatrix& region_sizes_mat, bool const reorder_sizes_mat);
RcppExport SEXP _redist_resample_plans_lowvar(SEXP normalized_weightsSEXP, SEXP plans_matSEXP, SEXP region_sizes_matSEXP, SEXP reorder_sizes_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type normalized_weights(normalized_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type plans_mat(plans_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type region_sizes_mat(region_sizes_matSEXP);
    Rcpp::traits::input_parameter< bool const >::type reorder_sizes_mat(reorder_sizes_matSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_plans_lowvar(normalized_weights, plans_mat, region_sizes_mat, reorder_sizes_mat));
    return rcpp_result_gen;
END_RCPP
}
// plan_joint
NumericMatrix plan_joint(IntegerVector m1, IntegerVector m2, NumericVector pop);
RcppExport SEXP _redist_plan_joint(SEXP m1SEXP, SEXP m2SEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(plan_joint(m1, m2, pop));
    return rcpp_result_gen;
END_RCPP
}
// renumber_matrix
IntegerMatrix renumber_matrix(IntegerMatrix plans, IntegerVector renumb);
RcppExport SEXP _redist_renumber_matrix(SEXP plansSEXP, SEXP renumbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type plans(plansSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type renumb(renumbSEXP);
    rcpp_result_gen = Rcpp::wrap(renumber_matrix(plans, renumb));
    return rcpp_result_gen;
END_RCPP
}
// solve_hungarian
IntegerMatrix solve_hungarian(NumericMatrix costMatrix);
RcppExport SEXP _redist_solve_hungarian(SEXP costMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type costMatrix(costMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_hungarian(costMatrix));
    return rcpp_result_gen;
END_RCPP
}
// rsg
List rsg(List adj_list, NumericVector population, int Ndistrict, double target_pop, double thresh, int maxiter);
RcppExport SEXP _redist_rsg(SEXP adj_listSEXP, SEXP populationSEXP, SEXP NdistrictSEXP, SEXP target_popSEXP, SEXP threshSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type population(populationSEXP);
    Rcpp::traits::input_parameter< int >::type Ndistrict(NdistrictSEXP);
    Rcpp::traits::input_parameter< double >::type target_pop(target_popSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(rsg(adj_list, population, Ndistrict, target_pop, thresh, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// k_smallest
NumericVector k_smallest(NumericMatrix x, int k);
RcppExport SEXP _redist_k_smallest(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(k_smallest(x, k));
    return rcpp_result_gen;
END_RCPP
}
// k_biggest
NumericVector k_biggest(NumericMatrix x, int k);
RcppExport SEXP _redist_k_biggest(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(k_biggest(x, k));
    return rcpp_result_gen;
END_RCPP
}
// run_redist_gsmc
List run_redist_gsmc(int const nsims, int const total_seats, int const ndists, Rcpp::IntegerVector const district_seat_sizes, int const initial_num_regions, List const& adj_list, arma::uvec const& counties, const arma::uvec& pop, Rcpp::CharacterVector const& step_types, double const target, double const lower, double const upper, double const rho, std::string const& sampling_space_str, List const& control, List const& constraints, int const verbosity, int const diagnostic_level, Rcpp::IntegerMatrix const& region_id_mat, Rcpp::IntegerMatrix const& region_sizes_mat);
RcppExport SEXP _redist_run_redist_gsmc(SEXP nsimsSEXP, SEXP total_seatsSEXP, SEXP ndistsSEXP, SEXP district_seat_sizesSEXP, SEXP initial_num_regionsSEXP, SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP step_typesSEXP, SEXP targetSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP rhoSEXP, SEXP sampling_space_strSEXP, SEXP controlSEXP, SEXP constraintsSEXP, SEXP verbositySEXP, SEXP diagnostic_levelSEXP, SEXP region_id_matSEXP, SEXP region_sizes_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int const >::type nsims(nsimsSEXP);
    Rcpp::traits::input_parameter< int const >::type total_seats(total_seatsSEXP);
    Rcpp::traits::input_parameter< int const >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector const >::type district_seat_sizes(district_seat_sizesSEXP);
    Rcpp::traits::input_parameter< int const >::type initial_num_regions(initial_num_regionsSEXP);
    Rcpp::traits::input_parameter< List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector const& >::type step_types(step_typesSEXP);
    Rcpp::traits::input_parameter< double const >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double const >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double const >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double const >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< std::string const& >::type sampling_space_str(sampling_space_strSEXP);
    Rcpp::traits::input_parameter< List const& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< List const& >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< int const >::type verbosity(verbositySEXP);
    Rcpp::traits::input_parameter< int const >::type diagnostic_level(diagnostic_levelSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_id_mat(region_id_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix const& >::type region_sizes_mat(region_sizes_matSEXP);
    rcpp_result_gen = Rcpp::wrap(run_redist_gsmc(nsims, total_seats, ndists, district_seat_sizes, initial_num_regions, adj_list, counties, pop, step_types, target, lower, upper, rho, sampling_space_str, control, constraints, verbosity, diagnostic_level, region_id_mat, region_sizes_mat));
    return rcpp_result_gen;
END_RCPP
}
// splits
IntegerVector splits(IntegerMatrix dm, IntegerVector community, int nd, int max_split);
RcppExport SEXP _redist_splits(SEXP dmSEXP, SEXP communitySEXP, SEXP ndSEXP, SEXP max_splitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type community(communitySEXP);
    Rcpp::traits::input_parameter< int >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int >::type max_split(max_splitSEXP);
    rcpp_result_gen = Rcpp::wrap(splits(dm, community, nd, max_split));
    return rcpp_result_gen;
END_RCPP
}
// dist_cty_splits
IntegerMatrix dist_cty_splits(IntegerMatrix dm, IntegerVector community, int nd);
RcppExport SEXP _redist_dist_cty_splits(SEXP dmSEXP, SEXP communitySEXP, SEXP ndSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type community(communitySEXP);
    Rcpp::traits::input_parameter< int >::type nd(ndSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_cty_splits(dm, community, nd));
    return rcpp_result_gen;
END_RCPP
}
// swMH
List swMH(List aList, NumericVector cdvec, NumericVector popvec, int nsims, List constraints, double eprob, double pct_dist_parity, NumericVector beta_sequence, NumericVector beta_weights, int lambda, double beta, std::string adapt_beta, int adjswap, int exact_mh, int adapt_eprob, int adapt_lambda, int num_hot_steps, int num_annealing_steps, int num_cold_steps, bool verbose);
RcppExport SEXP _redist_swMH(SEXP aListSEXP, SEXP cdvecSEXP, SEXP popvecSEXP, SEXP nsimsSEXP, SEXP constraintsSEXP, SEXP eprobSEXP, SEXP pct_dist_paritySEXP, SEXP beta_sequenceSEXP, SEXP beta_weightsSEXP, SEXP lambdaSEXP, SEXP betaSEXP, SEXP adapt_betaSEXP, SEXP adjswapSEXP, SEXP exact_mhSEXP, SEXP adapt_eprobSEXP, SEXP adapt_lambdaSEXP, SEXP num_hot_stepsSEXP, SEXP num_annealing_stepsSEXP, SEXP num_cold_stepsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type aList(aListSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cdvec(cdvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type popvec(popvecSEXP);
    Rcpp::traits::input_parameter< int >::type nsims(nsimsSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< double >::type eprob(eprobSEXP);
    Rcpp::traits::input_parameter< double >::type pct_dist_parity(pct_dist_paritySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_sequence(beta_sequenceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_weights(beta_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< std::string >::type adapt_beta(adapt_betaSEXP);
    Rcpp::traits::input_parameter< int >::type adjswap(adjswapSEXP);
    Rcpp::traits::input_parameter< int >::type exact_mh(exact_mhSEXP);
    Rcpp::traits::input_parameter< int >::type adapt_eprob(adapt_eprobSEXP);
    Rcpp::traits::input_parameter< int >::type adapt_lambda(adapt_lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type num_hot_steps(num_hot_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type num_annealing_steps(num_annealing_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type num_cold_steps(num_cold_stepsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(swMH(aList, cdvec, popvec, nsims, constraints, eprob, pct_dist_parity, beta_sequence, beta_weights, lambda, beta, adapt_beta, adjswap, exact_mh, adapt_eprob, adapt_lambda, num_hot_steps, num_annealing_steps, num_cold_steps, verbose));
    return rcpp_result_gen;
END_RCPP
}
// tree_pop
int tree_pop(Tree& ust, int vtx, const arma::uvec& pop, std::vector<int>& pop_below, std::vector<int>& parent);
RcppExport SEXP _redist_tree_pop(SEXP ustSEXP, SEXP vtxSEXP, SEXP popSEXP, SEXP pop_belowSEXP, SEXP parentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Tree& >::type ust(ustSEXP);
    Rcpp::traits::input_parameter< int >::type vtx(vtxSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type pop_below(pop_belowSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type parent(parentSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_pop(ust, vtx, pop, pop_below, parent));
    return rcpp_result_gen;
END_RCPP
}
// var_info_vec
NumericVector var_info_vec(IntegerMatrix m, IntegerVector ref, NumericVector pop);
RcppExport SEXP _redist_var_info_vec(SEXP mSEXP, SEXP refSEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ref(refSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(var_info_vec(m, ref, pop));
    return rcpp_result_gen;
END_RCPP
}
// sample_ust
Tree sample_ust(List l, const arma::uvec& pop, double lower, double upper, const arma::uvec& counties, const std::vector<bool> ignore);
RcppExport SEXP _redist_sample_ust(SEXP lSEXP, SEXP popSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP countiesSEXP, SEXP ignoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l(lSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const std::vector<bool> >::type ignore(ignoreSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_ust(l, pop, lower, upper, counties, ignore));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_redist_reduce_adj", (DL_FUNC) &_redist_reduce_adj, 3},
    {"_redist_collapse_adj", (DL_FUNC) &_redist_collapse_adj, 2},
    {"_redist_coarsen_adjacency", (DL_FUNC) &_redist_coarsen_adjacency, 2},
    {"_redist_get_plan_graph", (DL_FUNC) &_redist_get_plan_graph, 4},
    {"_redist_color_graph", (DL_FUNC) &_redist_color_graph, 2},
    {"_redist_polsbypopper", (DL_FUNC) &_redist_polsbypopper, 6},
    {"_redist_genAlConn", (DL_FUNC) &_redist_genAlConn, 2},
    {"_redist_findBoundary", (DL_FUNC) &_redist_findBoundary, 2},
    {"_redist_contiguity", (DL_FUNC) &_redist_contiguity, 2},
    {"_redist_cores", (DL_FUNC) &_redist_cores, 4},
    {"_redist_update_conncomp", (DL_FUNC) &_redist_update_conncomp, 3},
    {"_redist_crsg", (DL_FUNC) &_redist_crsg, 9},
    {"_redist_dist_dist_diff", (DL_FUNC) &_redist_dist_dist_diff, 7},
    {"_redist_get_region_multigraph", (DL_FUNC) &_redist_get_region_multigraph, 2},
    {"_redist_get_region_laplacian", (DL_FUNC) &_redist_get_region_laplacian, 2},
    {"_redist_get_log_number_linking_edges", (DL_FUNC) &_redist_get_log_number_linking_edges, 2},
    {"_redist_get_merged_log_number_linking_edges", (DL_FUNC) &_redist_get_merged_log_number_linking_edges, 4},
    {"_redist_log_st_map", (DL_FUNC) &_redist_log_st_map, 4},
    {"_redist_n_removed", (DL_FUNC) &_redist_n_removed, 3},
    {"_redist_countpartitions", (DL_FUNC) &_redist_countpartitions, 1},
    {"_redist_calcPWDh", (DL_FUNC) &_redist_calcPWDh, 1},
    {"_redist_draw_a_tree_on_a_region", (DL_FUNC) &_redist_draw_a_tree_on_a_region, 12},
    {"_redist_perform_a_valid_multidistrict_split", (DL_FUNC) &_redist_perform_a_valid_multidistrict_split, 17},
    {"_redist_draw_trees_on_a_region", (DL_FUNC) &_redist_draw_trees_on_a_region, 13},
    {"_redist_attempt_splits_on_a_region", (DL_FUNC) &_redist_attempt_splits_on_a_region, 16},
    {"_redist_compute_log_unnormalized_plan_target_density", (DL_FUNC) &_redist_compute_log_unnormalized_plan_target_density, 16},
    {"_redist_compute_log_unnormalized_region_target_density", (DL_FUNC) &_redist_compute_log_unnormalized_region_target_density, 16},
    {"_redist_compute_plans_log_optimal_weights", (DL_FUNC) &_redist_compute_plans_log_optimal_weights, 17},
    {"_redist_group_pct_top_k", (DL_FUNC) &_redist_group_pct_top_k, 5},
    {"_redist_proj_distr_m", (DL_FUNC) &_redist_proj_distr_m, 4},
    {"_redist_colmax", (DL_FUNC) &_redist_colmax, 1},
    {"_redist_colmin", (DL_FUNC) &_redist_colmin, 1},
    {"_redist_prec_cooccur", (DL_FUNC) &_redist_prec_cooccur, 3},
    {"_redist_group_pct", (DL_FUNC) &_redist_group_pct, 5},
    {"_redist_pop_tally", (DL_FUNC) &_redist_pop_tally, 4},
    {"_redist_infer_region_sizes", (DL_FUNC) &_redist_infer_region_sizes, 5},
    {"_redist_max_dev", (DL_FUNC) &_redist_max_dev, 4},
    {"_redist_order_district_stats", (DL_FUNC) &_redist_order_district_stats, 3},
    {"_redist_parallel_n_removed", (DL_FUNC) &_redist_parallel_n_removed, 4},
    {"_redist_parallel_effgap", (DL_FUNC) &_redist_parallel_effgap, 4},
    {"_redist_parallel_agg_p2d", (DL_FUNC) &_redist_parallel_agg_p2d, 4},
    {"_redist_parallel_biasatv", (DL_FUNC) &_redist_parallel_biasatv, 4},
    {"_redist_parallelDVS", (DL_FUNC) &_redist_parallelDVS, 3},
    {"_redist_parallel_splits", (DL_FUNC) &_redist_parallel_splits, 6},
    {"_redist_parallel_polsbypopper", (DL_FUNC) &_redist_parallel_polsbypopper, 7},
    {"_redist_ms_plans", (DL_FUNC) &_redist_ms_plans, 21},
    {"_redist_pareto_dominated", (DL_FUNC) &_redist_pareto_dominated, 1},
    {"_redist_random_cpp_testing", (DL_FUNC) &_redist_random_cpp_testing, 0},
    {"_redist_split_schedule_testing", (DL_FUNC) &_redist_split_schedule_testing, 1},
    {"_redist_matrix_reorder_testing", (DL_FUNC) &_redist_matrix_reorder_testing, 2},
    {"_redist_NEW_matrix_reorder_testing", (DL_FUNC) &_redist_NEW_matrix_reorder_testing, 2},
    {"_redist_more_random_cpp_testing", (DL_FUNC) &_redist_more_random_cpp_testing, 0},
    {"_redist_calc_county_dist_test", (DL_FUNC) &_redist_calc_county_dist_test, 4},
    {"_redist_calc_splits_test", (DL_FUNC) &_redist_calc_splits_test, 4},
    {"_redist_closest_adj_pop", (DL_FUNC) &_redist_closest_adj_pop, 3},
    {"_redist_rint1", (DL_FUNC) &_redist_rint1, 2},
    {"_redist_runif1", (DL_FUNC) &_redist_runif1, 2},
    {"_redist_resample_lowvar", (DL_FUNC) &_redist_resample_lowvar, 1},
    {"_redist_maximum_input_sizes", (DL_FUNC) &_redist_maximum_input_sizes, 0},
    {"_redist_get_canonical_plan_labelling", (DL_FUNC) &_redist_get_canonical_plan_labelling, 3},
    {"_redist_resample_plans_lowvar", (DL_FUNC) &_redist_resample_plans_lowvar, 4},
    {"_redist_plan_joint", (DL_FUNC) &_redist_plan_joint, 3},
    {"_redist_renumber_matrix", (DL_FUNC) &_redist_renumber_matrix, 2},
    {"_redist_solve_hungarian", (DL_FUNC) &_redist_solve_hungarian, 1},
    {"_redist_rsg", (DL_FUNC) &_redist_rsg, 6},
    {"_redist_k_smallest", (DL_FUNC) &_redist_k_smallest, 2},
    {"_redist_k_biggest", (DL_FUNC) &_redist_k_biggest, 2},
    {"_redist_run_redist_gsmc", (DL_FUNC) &_redist_run_redist_gsmc, 20},
    {"_redist_splits", (DL_FUNC) &_redist_splits, 4},
    {"_redist_dist_cty_splits", (DL_FUNC) &_redist_dist_cty_splits, 3},
    {"_redist_swMH", (DL_FUNC) &_redist_swMH, 20},
    {"_redist_tree_pop", (DL_FUNC) &_redist_tree_pop, 5},
    {"_redist_var_info_vec", (DL_FUNC) &_redist_var_info_vec, 3},
    {"_redist_sample_ust", (DL_FUNC) &_redist_sample_ust, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_redist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
