// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "gredist_types.h"
#include <RcppArmadillo.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_tree_prob_stuff
Rcpp::List test_tree_prob_stuff(List map_adj_list, const arma::uvec& counties, const arma::uvec& pop, int ndists, int num_regions, double target, double lower, double upper, const int min_potential_cut_size, const int max_potential_cut_size, arma::umat region_ids, arma::umat region_sizes, List forest_adj_list, bool split_district_only, bool verbose);
RcppExport SEXP _gredist_test_tree_prob_stuff(SEXP map_adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP ndistsSEXP, SEXP num_regionsSEXP, SEXP targetSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP min_potential_cut_sizeSEXP, SEXP max_potential_cut_sizeSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP forest_adj_listSEXP, SEXP split_district_onlySEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type map_adj_list(map_adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const int >::type min_potential_cut_size(min_potential_cut_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type max_potential_cut_size(max_potential_cut_sizeSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< List >::type forest_adj_list(forest_adj_listSEXP);
    Rcpp::traits::input_parameter< bool >::type split_district_only(split_district_onlySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(test_tree_prob_stuff(map_adj_list, counties, pop, ndists, num_regions, target, lower, upper, min_potential_cut_size, max_potential_cut_size, region_ids, region_sizes, forest_adj_list, split_district_only, verbose));
    return rcpp_result_gen;
END_RCPP
}
// reduce_adj
List reduce_adj(List adj_list, IntegerVector prec_map, int n_keep);
RcppExport SEXP _gredist_reduce_adj(SEXP adj_listSEXP, SEXP prec_mapSEXP, SEXP n_keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type prec_map(prec_mapSEXP);
    Rcpp::traits::input_parameter< int >::type n_keep(n_keepSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_adj(adj_list, prec_map, n_keep));
    return rcpp_result_gen;
END_RCPP
}
// collapse_adj
Graph collapse_adj(List graph, const arma::uvec& idxs);
RcppExport SEXP _gredist_collapse_adj(SEXP graphSEXP, SEXP idxsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type idxs(idxsSEXP);
    rcpp_result_gen = Rcpp::wrap(collapse_adj(graph, idxs));
    return rcpp_result_gen;
END_RCPP
}
// coarsen_adjacency
List coarsen_adjacency(List adj, IntegerVector groups);
RcppExport SEXP _gredist_coarsen_adjacency(SEXP adjSEXP, SEXP groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(coarsen_adjacency(adj, groups));
    return rcpp_result_gen;
END_RCPP
}
// get_plan_graph
std::vector<std::set<int>> get_plan_graph(List l, int V, IntegerVector plan, int n_distr);
RcppExport SEXP _gredist_get_plan_graph(SEXP lSEXP, SEXP VSEXP, SEXP planSEXP, SEXP n_distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l(lSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type plan(planSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    rcpp_result_gen = Rcpp::wrap(get_plan_graph(l, V, plan, n_distr));
    return rcpp_result_gen;
END_RCPP
}
// color_graph
IntegerVector color_graph(List l, IntegerVector plan);
RcppExport SEXP _gredist_color_graph(SEXP lSEXP, SEXP planSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l(lSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type plan(planSEXP);
    rcpp_result_gen = Rcpp::wrap(color_graph(l, plan));
    return rcpp_result_gen;
END_RCPP
}
// polsbypopper
NumericMatrix polsbypopper(IntegerVector from, IntegerVector to, NumericVector area, NumericVector perimeter, IntegerMatrix dm, int nd);
RcppExport SEXP _gredist_polsbypopper(SEXP fromSEXP, SEXP toSEXP, SEXP areaSEXP, SEXP perimeterSEXP, SEXP dmSEXP, SEXP ndSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type area(areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type perimeter(perimeterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< int >::type nd(ndSEXP);
    rcpp_result_gen = Rcpp::wrap(polsbypopper(from, to, area, perimeter, dm, nd));
    return rcpp_result_gen;
END_RCPP
}
// genAlConn
List genAlConn(List aList, NumericVector cds);
RcppExport SEXP _gredist_genAlConn(SEXP aListSEXP, SEXP cdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type aList(aListSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cds(cdsSEXP);
    rcpp_result_gen = Rcpp::wrap(genAlConn(aList, cds));
    return rcpp_result_gen;
END_RCPP
}
// findBoundary
NumericVector findBoundary(List fullList, List conList);
RcppExport SEXP _gredist_findBoundary(SEXP fullListSEXP, SEXP conListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type fullList(fullListSEXP);
    Rcpp::traits::input_parameter< List >::type conList(conListSEXP);
    rcpp_result_gen = Rcpp::wrap(findBoundary(fullList, conList));
    return rcpp_result_gen;
END_RCPP
}
// contiguity
IntegerVector contiguity(List adj, IntegerVector group);
RcppExport SEXP _gredist_contiguity(SEXP adjSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(contiguity(adj, group));
    return rcpp_result_gen;
END_RCPP
}
// cores
List cores(List adj, IntegerVector dm, int k, List cd_within_k);
RcppExport SEXP _gredist_cores(SEXP adjSEXP, SEXP dmSEXP, SEXP kSEXP, SEXP cd_within_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< List >::type cd_within_k(cd_within_kSEXP);
    rcpp_result_gen = Rcpp::wrap(cores(adj, dm, k, cd_within_k));
    return rcpp_result_gen;
END_RCPP
}
// update_conncomp
IntegerVector update_conncomp(IntegerVector dm, IntegerVector kvec, List adj);
RcppExport SEXP _gredist_update_conncomp(SEXP dmSEXP, SEXP kvecSEXP, SEXP adjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type kvec(kvecSEXP);
    Rcpp::traits::input_parameter< List >::type adj(adjSEXP);
    rcpp_result_gen = Rcpp::wrap(update_conncomp(dm, kvec, adj));
    return rcpp_result_gen;
END_RCPP
}
// crsg
List crsg(List adj_list, NumericVector population, NumericVector area, NumericVector x_center, NumericVector y_center, int Ndistrict, double target_pop, double thresh, int maxiter);
RcppExport SEXP _gredist_crsg(SEXP adj_listSEXP, SEXP populationSEXP, SEXP areaSEXP, SEXP x_centerSEXP, SEXP y_centerSEXP, SEXP NdistrictSEXP, SEXP target_popSEXP, SEXP threshSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type population(populationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type area(areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_center(x_centerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_center(y_centerSEXP);
    Rcpp::traits::input_parameter< int >::type Ndistrict(NdistrictSEXP);
    Rcpp::traits::input_parameter< double >::type target_pop(target_popSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(crsg(adj_list, population, area, x_center, y_center, Ndistrict, target_pop, thresh, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// dist_dist_diff
double dist_dist_diff(int p, int i_dist, int j_dist, NumericVector x_center, NumericVector y_center, NumericVector x, NumericVector y);
RcppExport SEXP _gredist_dist_dist_diff(SEXP pSEXP, SEXP i_distSEXP, SEXP j_distSEXP, SEXP x_centerSEXP, SEXP y_centerSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type i_dist(i_distSEXP);
    Rcpp::traits::input_parameter< int >::type j_dist(j_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_center(x_centerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_center(y_centerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dist_dist_diff(p, i_dist, j_dist, x_center, y_center, x, y));
    return rcpp_result_gen;
END_RCPP
}
// get_region_multigraph
RegionMultigraph get_region_multigraph(Rcpp::List const& adj_list, arma::uvec const& region_ids);
RcppExport SEXP _gredist_get_region_multigraph(SEXP adj_listSEXP, SEXP region_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type region_ids(region_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_region_multigraph(adj_list, region_ids));
    return rcpp_result_gen;
END_RCPP
}
// get_region_laplacian
arma::imat get_region_laplacian(Rcpp::List const& adj_list, arma::uvec const& region_ids);
RcppExport SEXP _gredist_get_region_laplacian(SEXP adj_listSEXP, SEXP region_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type region_ids(region_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_region_laplacian(adj_list, region_ids));
    return rcpp_result_gen;
END_RCPP
}
// get_log_number_linking_edges
double get_log_number_linking_edges(Rcpp::List const& adj_list, arma::uvec const& region_ids);
RcppExport SEXP _gredist_get_log_number_linking_edges(SEXP adj_listSEXP, SEXP region_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec const& >::type region_ids(region_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_log_number_linking_edges(adj_list, region_ids));
    return rcpp_result_gen;
END_RCPP
}
// run_redist_gsmc
List run_redist_gsmc(int const ndists, List const& adj_list, const arma::uvec& counties, const arma::uvec& pop, Rcpp::CharacterVector const& step_types, double const target, double const lower, double const upper, double rho, arma::umat region_id_mat, arma::umat region_sizes_mat, std::string const& sampling_space_str, List const& control, List const& constraints, int verbosity, bool diagnostic_mode);
RcppExport SEXP _gredist_run_redist_gsmc(SEXP ndistsSEXP, SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP step_typesSEXP, SEXP targetSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP rhoSEXP, SEXP region_id_matSEXP, SEXP region_sizes_matSEXP, SEXP sampling_space_strSEXP, SEXP controlSEXP, SEXP constraintsSEXP, SEXP verbositySEXP, SEXP diagnostic_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int const >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector const& >::type step_types(step_typesSEXP);
    Rcpp::traits::input_parameter< double const >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double const >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double const >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_id_mat(region_id_matSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_sizes_mat(region_sizes_matSEXP);
    Rcpp::traits::input_parameter< std::string const& >::type sampling_space_str(sampling_space_strSEXP);
    Rcpp::traits::input_parameter< List const& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< List const& >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< int >::type verbosity(verbositySEXP);
    Rcpp::traits::input_parameter< bool >::type diagnostic_mode(diagnostic_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(run_redist_gsmc(ndists, adj_list, counties, pop, step_types, target, lower, upper, rho, region_id_mat, region_sizes_mat, sampling_space_str, control, constraints, verbosity, diagnostic_mode));
    return rcpp_result_gen;
END_RCPP
}
// log_st_map
NumericVector log_st_map(const Graph& g, const arma::umat& districts, const arma::uvec& counties, int n_distr);
RcppExport SEXP _gredist_log_st_map(SEXP gSEXP, SEXP districtsSEXP, SEXP countiesSEXP, SEXP n_distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Graph& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    rcpp_result_gen = Rcpp::wrap(log_st_map(g, districts, counties, n_distr));
    return rcpp_result_gen;
END_RCPP
}
// n_removed
NumericVector n_removed(const Graph& g, const arma::umat& districts, int n_distr);
RcppExport SEXP _gredist_n_removed(SEXP gSEXP, SEXP districtsSEXP, SEXP n_distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Graph& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    rcpp_result_gen = Rcpp::wrap(n_removed(g, districts, n_distr));
    return rcpp_result_gen;
END_RCPP
}
// countpartitions
int countpartitions(List aList);
RcppExport SEXP _gredist_countpartitions(SEXP aListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type aList(aListSEXP);
    rcpp_result_gen = Rcpp::wrap(countpartitions(aList));
    return rcpp_result_gen;
END_RCPP
}
// calcPWDh
NumericMatrix calcPWDh(NumericMatrix x);
RcppExport SEXP _gredist_calcPWDh(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calcPWDh(x));
    return rcpp_result_gen;
END_RCPP
}
// draw_a_tree_on_a_region
List draw_a_tree_on_a_region(List adj_list, const arma::uvec& counties, const arma::uvec& pop, int ndists, int num_regions, int num_districts, int region_id_to_draw_tree_on, double lower, double upper, arma::umat region_ids, arma::umat region_sizes, bool verbose);
RcppExport SEXP _gredist_draw_a_tree_on_a_region(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP ndistsSEXP, SEXP num_regionsSEXP, SEXP num_districtsSEXP, SEXP region_id_to_draw_tree_onSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< int >::type num_districts(num_districtsSEXP);
    Rcpp::traits::input_parameter< int >::type region_id_to_draw_tree_on(region_id_to_draw_tree_onSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(draw_a_tree_on_a_region(adj_list, counties, pop, ndists, num_regions, num_districts, region_id_to_draw_tree_on, lower, upper, region_ids, region_sizes, verbose));
    return rcpp_result_gen;
END_RCPP
}
// perform_a_valid_multidistrict_split
List perform_a_valid_multidistrict_split(List adj_list, const arma::uvec& counties, const arma::uvec& pop, int ndists, int num_regions, int num_districts, int region_id_to_split, double target, double lower, double upper, arma::umat region_ids, arma::umat region_sizes, int split_dval_min, int split_dval_max, bool split_district_only, bool verbose, int k_param);
RcppExport SEXP _gredist_perform_a_valid_multidistrict_split(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP ndistsSEXP, SEXP num_regionsSEXP, SEXP num_districtsSEXP, SEXP region_id_to_splitSEXP, SEXP targetSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP split_dval_minSEXP, SEXP split_dval_maxSEXP, SEXP split_district_onlySEXP, SEXP verboseSEXP, SEXP k_paramSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< int >::type num_districts(num_districtsSEXP);
    Rcpp::traits::input_parameter< int >::type region_id_to_split(region_id_to_splitSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< int >::type split_dval_min(split_dval_minSEXP);
    Rcpp::traits::input_parameter< int >::type split_dval_max(split_dval_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type split_district_only(split_district_onlySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type k_param(k_paramSEXP);
    rcpp_result_gen = Rcpp::wrap(perform_a_valid_multidistrict_split(adj_list, counties, pop, ndists, num_regions, num_districts, region_id_to_split, target, lower, upper, region_ids, region_sizes, split_dval_min, split_dval_max, split_district_only, verbose, k_param));
    return rcpp_result_gen;
END_RCPP
}
// perform_merge_split_steps
List perform_merge_split_steps(List adj_list, const arma::uvec& counties, const arma::uvec& pop, int k_param, double target, double lower, double upper, int ndists, int num_regions, int num_districts, arma::umat region_ids, arma::umat region_sizes, std::vector<int> region_pops, bool split_district_only, int num_merge_split_steps, bool verbose);
RcppExport SEXP _gredist_perform_merge_split_steps(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP k_paramSEXP, SEXP targetSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP ndistsSEXP, SEXP num_regionsSEXP, SEXP num_districtsSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP region_popsSEXP, SEXP split_district_onlySEXP, SEXP num_merge_split_stepsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int >::type k_param(k_paramSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< int >::type num_districts(num_districtsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type region_pops(region_popsSEXP);
    Rcpp::traits::input_parameter< bool >::type split_district_only(split_district_onlySEXP);
    Rcpp::traits::input_parameter< int >::type num_merge_split_steps(num_merge_split_stepsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(perform_merge_split_steps(adj_list, counties, pop, k_param, target, lower, upper, ndists, num_regions, num_districts, region_ids, region_sizes, region_pops, split_district_only, num_merge_split_steps, verbose));
    return rcpp_result_gen;
END_RCPP
}
// compute_a_log_optimal_weight
double compute_a_log_optimal_weight(List adj_list, const arma::uvec& counties, const arma::uvec& pop, List control, int ndists, int num_regions, double lower, double target, double upper, arma::umat region_ids, arma::umat region_sizes);
RcppExport SEXP _gredist_compute_a_log_optimal_weight(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP controlSEXP, SEXP ndistsSEXP, SEXP num_regionsSEXP, SEXP lowerSEXP, SEXP targetSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< int >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_sizes(region_sizesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_a_log_optimal_weight(adj_list, counties, pop, control, ndists, num_regions, lower, target, upper, region_ids, region_sizes));
    return rcpp_result_gen;
END_RCPP
}
// compute_log_unnormalized_plan_target_density
arma::vec compute_log_unnormalized_plan_target_density(List adj_list, const arma::uvec& counties, const arma::uvec& pop, List const& constraints, double pop_temper, double rho, int ndists, int num_regions, double lower, double target, double upper, arma::umat region_ids, arma::umat region_sizes, int num_threads);
RcppExport SEXP _gredist_compute_log_unnormalized_plan_target_density(SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP constraintsSEXP, SEXP pop_temperSEXP, SEXP rhoSEXP, SEXP ndistsSEXP, SEXP num_regionsSEXP, SEXP lowerSEXP, SEXP targetSEXP, SEXP upperSEXP, SEXP region_idsSEXP, SEXP region_sizesSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< List const& >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< double >::type pop_temper(pop_temperSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< int >::type num_regions(num_regionsSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_ids(region_idsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_sizes(region_sizesSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_log_unnormalized_plan_target_density(adj_list, counties, pop, constraints, pop_temper, rho, ndists, num_regions, lower, target, upper, region_ids, region_sizes, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// group_pct_top_k
NumericVector group_pct_top_k(const IntegerMatrix m, const NumericVector group_pop, const NumericVector total_pop, int k, int n_distr);
RcppExport SEXP _gredist_group_pct_top_k(SEXP mSEXP, SEXP group_popSEXP, SEXP total_popSEXP, SEXP kSEXP, SEXP n_distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type group_pop(group_popSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type total_pop(total_popSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    rcpp_result_gen = Rcpp::wrap(group_pct_top_k(m, group_pop, total_pop, k, n_distr));
    return rcpp_result_gen;
END_RCPP
}
// proj_distr_m
NumericMatrix proj_distr_m(IntegerMatrix districts, const arma::vec x, IntegerVector draw_idx, int n_distr);
RcppExport SEXP _gredist_proj_distr_m(SEXP districtsSEXP, SEXP xSEXP, SEXP draw_idxSEXP, SEXP n_distrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type draw_idx(draw_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    rcpp_result_gen = Rcpp::wrap(proj_distr_m(districts, x, draw_idx, n_distr));
    return rcpp_result_gen;
END_RCPP
}
// colmax
NumericVector colmax(const NumericMatrix x);
RcppExport SEXP _gredist_colmax(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colmax(x));
    return rcpp_result_gen;
END_RCPP
}
// colmin
NumericVector colmin(const NumericMatrix x);
RcppExport SEXP _gredist_colmin(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colmin(x));
    return rcpp_result_gen;
END_RCPP
}
// prec_cooccur
arma::mat prec_cooccur(arma::umat m, arma::uvec idxs, int ncores);
RcppExport SEXP _gredist_prec_cooccur(SEXP mSEXP, SEXP idxsSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type idxs(idxsSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(prec_cooccur(m, idxs, ncores));
    return rcpp_result_gen;
END_RCPP
}
// group_pct
NumericMatrix group_pct(IntegerMatrix const& plans_mat, arma::vec const& group_pop, arma::vec const& total_pop, int const n_distr, int const num_threads);
RcppExport SEXP _gredist_group_pct(SEXP plans_matSEXP, SEXP group_popSEXP, SEXP total_popSEXP, SEXP n_distrSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix const& >::type plans_mat(plans_matSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type group_pop(group_popSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type total_pop(total_popSEXP);
    Rcpp::traits::input_parameter< int const >::type n_distr(n_distrSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(group_pct(plans_mat, group_pop, total_pop, n_distr, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// pop_tally
NumericMatrix pop_tally(IntegerMatrix const& districts, arma::vec const& pop, int const n_distr, int const num_threads);
RcppExport SEXP _gredist_pop_tally(SEXP districtsSEXP, SEXP popSEXP, SEXP n_distrSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix const& >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int const >::type n_distr(n_distrSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pop_tally(districts, pop, n_distr, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// max_dev
NumericVector max_dev(const IntegerMatrix& districts, const arma::vec& pop, int const n_distr, int const num_threads);
RcppExport SEXP _gredist_max_dev(SEXP districtsSEXP, SEXP popSEXP, SEXP n_distrSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int const >::type n_distr(n_distrSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(max_dev(districts, pop, n_distr, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_n_removed
NumericVector parallel_n_removed(const Graph& g, const IntegerMatrix& districts, int const n_distr, int const num_threads);
RcppExport SEXP _gredist_parallel_n_removed(SEXP gSEXP, SEXP districtsSEXP, SEXP n_distrSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Graph& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< int const >::type n_distr(n_distrSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_n_removed(g, districts, n_distr, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_effgap
NumericVector parallel_effgap(NumericMatrix const& dcounts, NumericMatrix const& rcounts, int const totvote, int const num_threads);
RcppExport SEXP _gredist_parallel_effgap(SEXP dcountsSEXP, SEXP rcountsSEXP, SEXP totvoteSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix const& >::type dcounts(dcountsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix const& >::type rcounts(rcountsSEXP);
    Rcpp::traits::input_parameter< int const >::type totvote(totvoteSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_effgap(dcounts, rcounts, totvote, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_agg_p2d
NumericMatrix parallel_agg_p2d(IntegerMatrix const& dm, NumericVector const& vote, int const nd, int const num_threads);
RcppExport SEXP _gredist_parallel_agg_p2d(SEXP dmSEXP, SEXP voteSEXP, SEXP ndSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< IntegerMatrix const& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type vote(voteSEXP);
    Rcpp::traits::input_parameter< int const >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_agg_p2d(dm, vote, nd, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_biasatv
NumericVector parallel_biasatv(NumericMatrix const& dvs, double const v, int const nd, int const num_threads);
RcppExport SEXP _gredist_parallel_biasatv(SEXP dvsSEXP, SEXP vSEXP, SEXP ndSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix const& >::type dvs(dvsSEXP);
    Rcpp::traits::input_parameter< double const >::type v(vSEXP);
    Rcpp::traits::input_parameter< int const >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_biasatv(dvs, v, nd, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallelDVS
NumericMatrix parallelDVS(NumericMatrix const& dcounts, NumericMatrix const& rcounts, int const num_threads);
RcppExport SEXP _gredist_parallelDVS(SEXP dcountsSEXP, SEXP rcountsSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix const& >::type dcounts(dcountsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix const& >::type rcounts(rcountsSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallelDVS(dcounts, rcounts, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_splits
Rcpp::IntegerVector parallel_splits(const IntegerMatrix& dm, const IntegerVector& community, int const nd, int const max_split, int const num_threads, bool const skip_last);
RcppExport SEXP _gredist_parallel_splits(SEXP dmSEXP, SEXP communitySEXP, SEXP ndSEXP, SEXP max_splitSEXP, SEXP num_threadsSEXP, SEXP skip_lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type community(communitySEXP);
    Rcpp::traits::input_parameter< int const >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int const >::type max_split(max_splitSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool const >::type skip_last(skip_lastSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_splits(dm, community, nd, max_split, num_threads, skip_last));
    return rcpp_result_gen;
END_RCPP
}
// parallel_polsbypopper
NumericMatrix parallel_polsbypopper(IntegerVector const& from, IntegerVector const& to, NumericVector const& area, NumericVector const& perimeter, IntegerMatrix const& dm, int const nd, int const num_threads);
RcppExport SEXP _gredist_parallel_polsbypopper(SEXP fromSEXP, SEXP toSEXP, SEXP areaSEXP, SEXP perimeterSEXP, SEXP dmSEXP, SEXP ndSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< IntegerVector const& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector const& >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type area(areaSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type perimeter(perimeterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix const& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< int const >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int const >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_polsbypopper(from, to, area, perimeter, dm, nd, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// ms_plans
Rcpp::List ms_plans(int nsims, int warmup, int thin, int const ndists, List const& adj_list, const arma::uvec& counties, const arma::uvec& pop, double const target, double const lower, double const upper, double rho, arma::umat region_id_mat, arma::umat region_sizes_mat, std::string const& sampling_space_str, std::string const& merge_prob_type, List const& control, List const& constraints, int verbosity, bool diagnostic_mode);
RcppExport SEXP _gredist_ms_plans(SEXP nsimsSEXP, SEXP warmupSEXP, SEXP thinSEXP, SEXP ndistsSEXP, SEXP adj_listSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP targetSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP rhoSEXP, SEXP region_id_matSEXP, SEXP region_sizes_matSEXP, SEXP sampling_space_strSEXP, SEXP merge_prob_typeSEXP, SEXP controlSEXP, SEXP constraintsSEXP, SEXP verbositySEXP, SEXP diagnostic_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nsims(nsimsSEXP);
    Rcpp::traits::input_parameter< int >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int const >::type ndists(ndistsSEXP);
    Rcpp::traits::input_parameter< List const& >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< double const >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double const >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double const >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_id_mat(region_id_matSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type region_sizes_mat(region_sizes_matSEXP);
    Rcpp::traits::input_parameter< std::string const& >::type sampling_space_str(sampling_space_strSEXP);
    Rcpp::traits::input_parameter< std::string const& >::type merge_prob_type(merge_prob_typeSEXP);
    Rcpp::traits::input_parameter< List const& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< List const& >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< int >::type verbosity(verbositySEXP);
    Rcpp::traits::input_parameter< bool >::type diagnostic_mode(diagnostic_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(ms_plans(nsims, warmup, thin, ndists, adj_list, counties, pop, target, lower, upper, rho, region_id_mat, region_sizes_mat, sampling_space_str, merge_prob_type, control, constraints, verbosity, diagnostic_mode));
    return rcpp_result_gen;
END_RCPP
}
// pareto_dominated
LogicalVector pareto_dominated(arma::mat x);
RcppExport SEXP _gredist_pareto_dominated(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pareto_dominated(x));
    return rcpp_result_gen;
END_RCPP
}
// closest_adj_pop
int closest_adj_pop(IntegerVector adj, int i_dist, NumericVector g_prop);
RcppExport SEXP _gredist_closest_adj_pop(SEXP adjSEXP, SEXP i_distSEXP, SEXP g_propSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< int >::type i_dist(i_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g_prop(g_propSEXP);
    rcpp_result_gen = Rcpp::wrap(closest_adj_pop(adj, i_dist, g_prop));
    return rcpp_result_gen;
END_RCPP
}
// rint1
Rcpp::IntegerVector rint1(int n, int max);
RcppExport SEXP _gredist_rint1(SEXP nSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(rint1(n, max));
    return rcpp_result_gen;
END_RCPP
}
// runif1
Rcpp::NumericVector runif1(int n, int max);
RcppExport SEXP _gredist_runif1(SEXP nSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(runif1(n, max));
    return rcpp_result_gen;
END_RCPP
}
// resample_lowvar
arma::ivec resample_lowvar(arma::vec wgts);
RcppExport SEXP _gredist_resample_lowvar(SEXP wgtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type wgts(wgtsSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_lowvar(wgts));
    return rcpp_result_gen;
END_RCPP
}
// plan_joint
NumericMatrix plan_joint(IntegerVector m1, IntegerVector m2, NumericVector pop);
RcppExport SEXP _gredist_plan_joint(SEXP m1SEXP, SEXP m2SEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(plan_joint(m1, m2, pop));
    return rcpp_result_gen;
END_RCPP
}
// renumber_matrix
IntegerMatrix renumber_matrix(IntegerMatrix plans, IntegerVector renumb);
RcppExport SEXP _gredist_renumber_matrix(SEXP plansSEXP, SEXP renumbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type plans(plansSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type renumb(renumbSEXP);
    rcpp_result_gen = Rcpp::wrap(renumber_matrix(plans, renumb));
    return rcpp_result_gen;
END_RCPP
}
// solve_hungarian
IntegerMatrix solve_hungarian(NumericMatrix costMatrix);
RcppExport SEXP _gredist_solve_hungarian(SEXP costMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type costMatrix(costMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_hungarian(costMatrix));
    return rcpp_result_gen;
END_RCPP
}
// rsg
List rsg(List adj_list, NumericVector population, int Ndistrict, double target_pop, double thresh, int maxiter);
RcppExport SEXP _gredist_rsg(SEXP adj_listSEXP, SEXP populationSEXP, SEXP NdistrictSEXP, SEXP target_popSEXP, SEXP threshSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type population(populationSEXP);
    Rcpp::traits::input_parameter< int >::type Ndistrict(NdistrictSEXP);
    Rcpp::traits::input_parameter< double >::type target_pop(target_popSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(rsg(adj_list, population, Ndistrict, target_pop, thresh, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// k_smallest
NumericVector k_smallest(NumericMatrix x, int k);
RcppExport SEXP _gredist_k_smallest(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(k_smallest(x, k));
    return rcpp_result_gen;
END_RCPP
}
// k_biggest
NumericVector k_biggest(NumericMatrix x, int k);
RcppExport SEXP _gredist_k_biggest(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(k_biggest(x, k));
    return rcpp_result_gen;
END_RCPP
}
// smc_plans
List smc_plans(int N, List l, const arma::uvec& counties, const arma::uvec& pop, int n_distr, double target, double lower, double upper, double rho, arma::umat districts, int n_drawn, int n_steps, List constraints, List control, int verbosity);
RcppExport SEXP _gredist_smc_plans(SEXP NSEXP, SEXP lSEXP, SEXP countiesSEXP, SEXP popSEXP, SEXP n_distrSEXP, SEXP targetSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP rhoSEXP, SEXP districtsSEXP, SEXP n_drawnSEXP, SEXP n_stepsSEXP, SEXP constraintsSEXP, SEXP controlSEXP, SEXP verbositySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< List >::type l(lSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< int >::type n_distr(n_distrSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type districts(districtsSEXP);
    Rcpp::traits::input_parameter< int >::type n_drawn(n_drawnSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< int >::type verbosity(verbositySEXP);
    rcpp_result_gen = Rcpp::wrap(smc_plans(N, l, counties, pop, n_distr, target, lower, upper, rho, districts, n_drawn, n_steps, constraints, control, verbosity));
    return rcpp_result_gen;
END_RCPP
}
// splits
IntegerVector splits(IntegerMatrix dm, IntegerVector community, int nd, int max_split);
RcppExport SEXP _gredist_splits(SEXP dmSEXP, SEXP communitySEXP, SEXP ndSEXP, SEXP max_splitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type community(communitySEXP);
    Rcpp::traits::input_parameter< int >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int >::type max_split(max_splitSEXP);
    rcpp_result_gen = Rcpp::wrap(splits(dm, community, nd, max_split));
    return rcpp_result_gen;
END_RCPP
}
// dist_cty_splits
IntegerMatrix dist_cty_splits(IntegerMatrix dm, IntegerVector community, int nd);
RcppExport SEXP _gredist_dist_cty_splits(SEXP dmSEXP, SEXP communitySEXP, SEXP ndSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type community(communitySEXP);
    Rcpp::traits::input_parameter< int >::type nd(ndSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_cty_splits(dm, community, nd));
    return rcpp_result_gen;
END_RCPP
}
// swMH
List swMH(List aList, NumericVector cdvec, NumericVector popvec, int nsims, List constraints, double eprob, double pct_dist_parity, NumericVector beta_sequence, NumericVector beta_weights, int lambda, double beta, std::string adapt_beta, int adjswap, int exact_mh, int adapt_eprob, int adapt_lambda, int num_hot_steps, int num_annealing_steps, int num_cold_steps, bool verbose);
RcppExport SEXP _gredist_swMH(SEXP aListSEXP, SEXP cdvecSEXP, SEXP popvecSEXP, SEXP nsimsSEXP, SEXP constraintsSEXP, SEXP eprobSEXP, SEXP pct_dist_paritySEXP, SEXP beta_sequenceSEXP, SEXP beta_weightsSEXP, SEXP lambdaSEXP, SEXP betaSEXP, SEXP adapt_betaSEXP, SEXP adjswapSEXP, SEXP exact_mhSEXP, SEXP adapt_eprobSEXP, SEXP adapt_lambdaSEXP, SEXP num_hot_stepsSEXP, SEXP num_annealing_stepsSEXP, SEXP num_cold_stepsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type aList(aListSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cdvec(cdvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type popvec(popvecSEXP);
    Rcpp::traits::input_parameter< int >::type nsims(nsimsSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< double >::type eprob(eprobSEXP);
    Rcpp::traits::input_parameter< double >::type pct_dist_parity(pct_dist_paritySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_sequence(beta_sequenceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_weights(beta_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< std::string >::type adapt_beta(adapt_betaSEXP);
    Rcpp::traits::input_parameter< int >::type adjswap(adjswapSEXP);
    Rcpp::traits::input_parameter< int >::type exact_mh(exact_mhSEXP);
    Rcpp::traits::input_parameter< int >::type adapt_eprob(adapt_eprobSEXP);
    Rcpp::traits::input_parameter< int >::type adapt_lambda(adapt_lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type num_hot_steps(num_hot_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type num_annealing_steps(num_annealing_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type num_cold_steps(num_cold_stepsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(swMH(aList, cdvec, popvec, nsims, constraints, eprob, pct_dist_parity, beta_sequence, beta_weights, lambda, beta, adapt_beta, adjswap, exact_mh, adapt_eprob, adapt_lambda, num_hot_steps, num_annealing_steps, num_cold_steps, verbose));
    return rcpp_result_gen;
END_RCPP
}
// tree_pop
int tree_pop(Tree& ust, int vtx, const arma::uvec& pop, std::vector<int>& pop_below, std::vector<int>& parent);
RcppExport SEXP _gredist_tree_pop(SEXP ustSEXP, SEXP vtxSEXP, SEXP popSEXP, SEXP pop_belowSEXP, SEXP parentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Tree& >::type ust(ustSEXP);
    Rcpp::traits::input_parameter< int >::type vtx(vtxSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type pop_below(pop_belowSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type parent(parentSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_pop(ust, vtx, pop, pop_below, parent));
    return rcpp_result_gen;
END_RCPP
}
// var_info_vec
NumericVector var_info_vec(IntegerMatrix m, IntegerVector ref, NumericVector pop);
RcppExport SEXP _gredist_var_info_vec(SEXP mSEXP, SEXP refSEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ref(refSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(var_info_vec(m, ref, pop));
    return rcpp_result_gen;
END_RCPP
}
// sample_ust
Tree sample_ust(List l, const arma::uvec& pop, double lower, double upper, const arma::uvec& counties, const std::vector<bool> ignore);
RcppExport SEXP _gredist_sample_ust(SEXP lSEXP, SEXP popSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP countiesSEXP, SEXP ignoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l(lSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type counties(countiesSEXP);
    Rcpp::traits::input_parameter< const std::vector<bool> >::type ignore(ignoreSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_ust(l, pop, lower, upper, counties, ignore));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gredist_test_tree_prob_stuff", (DL_FUNC) &_gredist_test_tree_prob_stuff, 15},
    {"_gredist_reduce_adj", (DL_FUNC) &_gredist_reduce_adj, 3},
    {"_gredist_collapse_adj", (DL_FUNC) &_gredist_collapse_adj, 2},
    {"_gredist_coarsen_adjacency", (DL_FUNC) &_gredist_coarsen_adjacency, 2},
    {"_gredist_get_plan_graph", (DL_FUNC) &_gredist_get_plan_graph, 4},
    {"_gredist_color_graph", (DL_FUNC) &_gredist_color_graph, 2},
    {"_gredist_polsbypopper", (DL_FUNC) &_gredist_polsbypopper, 6},
    {"_gredist_genAlConn", (DL_FUNC) &_gredist_genAlConn, 2},
    {"_gredist_findBoundary", (DL_FUNC) &_gredist_findBoundary, 2},
    {"_gredist_contiguity", (DL_FUNC) &_gredist_contiguity, 2},
    {"_gredist_cores", (DL_FUNC) &_gredist_cores, 4},
    {"_gredist_update_conncomp", (DL_FUNC) &_gredist_update_conncomp, 3},
    {"_gredist_crsg", (DL_FUNC) &_gredist_crsg, 9},
    {"_gredist_dist_dist_diff", (DL_FUNC) &_gredist_dist_dist_diff, 7},
    {"_gredist_get_region_multigraph", (DL_FUNC) &_gredist_get_region_multigraph, 2},
    {"_gredist_get_region_laplacian", (DL_FUNC) &_gredist_get_region_laplacian, 2},
    {"_gredist_get_log_number_linking_edges", (DL_FUNC) &_gredist_get_log_number_linking_edges, 2},
    {"_gredist_run_redist_gsmc", (DL_FUNC) &_gredist_run_redist_gsmc, 16},
    {"_gredist_log_st_map", (DL_FUNC) &_gredist_log_st_map, 4},
    {"_gredist_n_removed", (DL_FUNC) &_gredist_n_removed, 3},
    {"_gredist_countpartitions", (DL_FUNC) &_gredist_countpartitions, 1},
    {"_gredist_calcPWDh", (DL_FUNC) &_gredist_calcPWDh, 1},
    {"_gredist_draw_a_tree_on_a_region", (DL_FUNC) &_gredist_draw_a_tree_on_a_region, 12},
    {"_gredist_perform_a_valid_multidistrict_split", (DL_FUNC) &_gredist_perform_a_valid_multidistrict_split, 17},
    {"_gredist_perform_merge_split_steps", (DL_FUNC) &_gredist_perform_merge_split_steps, 16},
    {"_gredist_compute_a_log_optimal_weight", (DL_FUNC) &_gredist_compute_a_log_optimal_weight, 11},
    {"_gredist_compute_log_unnormalized_plan_target_density", (DL_FUNC) &_gredist_compute_log_unnormalized_plan_target_density, 14},
    {"_gredist_group_pct_top_k", (DL_FUNC) &_gredist_group_pct_top_k, 5},
    {"_gredist_proj_distr_m", (DL_FUNC) &_gredist_proj_distr_m, 4},
    {"_gredist_colmax", (DL_FUNC) &_gredist_colmax, 1},
    {"_gredist_colmin", (DL_FUNC) &_gredist_colmin, 1},
    {"_gredist_prec_cooccur", (DL_FUNC) &_gredist_prec_cooccur, 3},
    {"_gredist_group_pct", (DL_FUNC) &_gredist_group_pct, 5},
    {"_gredist_pop_tally", (DL_FUNC) &_gredist_pop_tally, 4},
    {"_gredist_max_dev", (DL_FUNC) &_gredist_max_dev, 4},
    {"_gredist_parallel_n_removed", (DL_FUNC) &_gredist_parallel_n_removed, 4},
    {"_gredist_parallel_effgap", (DL_FUNC) &_gredist_parallel_effgap, 4},
    {"_gredist_parallel_agg_p2d", (DL_FUNC) &_gredist_parallel_agg_p2d, 4},
    {"_gredist_parallel_biasatv", (DL_FUNC) &_gredist_parallel_biasatv, 4},
    {"_gredist_parallelDVS", (DL_FUNC) &_gredist_parallelDVS, 3},
    {"_gredist_parallel_splits", (DL_FUNC) &_gredist_parallel_splits, 6},
    {"_gredist_parallel_polsbypopper", (DL_FUNC) &_gredist_parallel_polsbypopper, 7},
    {"_gredist_ms_plans", (DL_FUNC) &_gredist_ms_plans, 19},
    {"_gredist_pareto_dominated", (DL_FUNC) &_gredist_pareto_dominated, 1},
    {"_gredist_closest_adj_pop", (DL_FUNC) &_gredist_closest_adj_pop, 3},
    {"_gredist_rint1", (DL_FUNC) &_gredist_rint1, 2},
    {"_gredist_runif1", (DL_FUNC) &_gredist_runif1, 2},
    {"_gredist_resample_lowvar", (DL_FUNC) &_gredist_resample_lowvar, 1},
    {"_gredist_plan_joint", (DL_FUNC) &_gredist_plan_joint, 3},
    {"_gredist_renumber_matrix", (DL_FUNC) &_gredist_renumber_matrix, 2},
    {"_gredist_solve_hungarian", (DL_FUNC) &_gredist_solve_hungarian, 1},
    {"_gredist_rsg", (DL_FUNC) &_gredist_rsg, 6},
    {"_gredist_k_smallest", (DL_FUNC) &_gredist_k_smallest, 2},
    {"_gredist_k_biggest", (DL_FUNC) &_gredist_k_biggest, 2},
    {"_gredist_smc_plans", (DL_FUNC) &_gredist_smc_plans, 15},
    {"_gredist_splits", (DL_FUNC) &_gredist_splits, 4},
    {"_gredist_dist_cty_splits", (DL_FUNC) &_gredist_dist_cty_splits, 3},
    {"_gredist_swMH", (DL_FUNC) &_gredist_swMH, 20},
    {"_gredist_tree_pop", (DL_FUNC) &_gredist_tree_pop, 5},
    {"_gredist_var_info_vec", (DL_FUNC) &_gredist_var_info_vec, 3},
    {"_gredist_sample_ust", (DL_FUNC) &_gredist_sample_ust, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_gredist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
